<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333333;
            margin: 0;
            padding: 0;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            border-bottom: 3px solid #dc2626; /* Clean Red */
            padding-bottom: 20px;
            margin-bottom: 25px;
        }
        .header-table {
            width: 100%;
            border-collapse: collapse;
        }
        .header-logo {
            font-size: 24px;
            font-weight: bold;
            color: #dc2626;
            margin: 0;
        }
        .header-title {
            font-size: 18px;
            font-weight: bold;
            color: #1f2937;
            margin-top: 5px;
        }
        .header-meta {
            text-align: right;
            color: #6b7280;
            font-size: 11px;
        }
        .report-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        .report-table th {
            background-color: #1f2937; /* Dark Grey */
            color: #ffffff;
            font-weight: bold;
            padding: 10px 12px;
            text-align: left;
            text-transform: uppercase;
            font-size: 10px;
            letter-spacing: 0.5px;
            border: 1px solid #1f2937;
        }
        .report-table td {
            padding: 8px 12px;
            border: 1px solid #e5e7eb;
        }
        .report-table tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .text-right {
            text-align: right !important;
        }
        .text-center {
            text-align: center !important;
        }
        .font-bold {
            font-weight: bold;
        }
        .text-danger {
            color: #dc2626;
            font-weight: bold;
        }
        .text-success {
            color: #059669;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
        .total-row {
            background-color: #f3f4f6 !important;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <div class="header">
        <table class="header-table">
            <tr>
                <td>
                    <div class="header-logo">AIWA AGENCY</div>
                    <div class="header-title">{{ $title }}</div>
                </td>
                <td class="header-meta">
                    <strong>Generated on:</strong> {{ $date }}<br>
                    <strong>Generated by:</strong> {{ $user->name }} ({{ ucfirst($user->role) }})<br>
                    <strong>Scope:</strong> {{ $user->role === 'staff' ? 'Assigned Clients Only' : 'Agency-Wide' }}
                </td>
            </tr>
        </table>
    </div>

    <table class="report-table">
        <thead>
            @if($reportType === 'client_dues')
                <tr>
                    <th>Client Name</th>
                    <th>Company Name</th>
                    <th class="text-center">Services Count</th>
                    <th class="text-right">Total Value</th>
                    <th class="text-right">Total Paid</th>
                    <th class="text-right">Balance Due</th>
                </tr>
            @elseif($reportType === 'service_revenue')
                <tr>
                    <th>Service Type</th>
                    <th class="text-center">Active Count</th>
                    <th class="text-right">Value (excl. VAT)</th>
                    <th class="text-right">Total (incl. VAT)</th>
                    <th class="text-right">Paid Amount</th>
                    <th class="text-right">Balance Due</th>
                </tr>
            @elseif($reportType === 'monthly_renewals')
                <tr>
                    <th>Renewal Month</th>
                    <th class="text-center">Accounts Renewing</th>
                    <th class="text-right">Renewal Value</th>
                    <th class="text-center">Fully Paid</th>
                    <th class="text-center">Pending Payments</th>
                </tr>
            @elseif($reportType === 'vat_summary')
                <tr>
                    <th>VAT Paid Status</th>
                    <th class="text-center">Service Count</th>
                    <th class="text-right">VAT Amount</th>
                </tr>
            @elseif($reportType === 'pending_payments')
                <tr>
                    <th>Client Name</th>
                    <th>Company Name</th>
                    <th>Service Type</th>
                    <th class="text-center">Expiry Date</th>
                    <th class="text-right">Total Value</th>
                    <th class="text-right">Paid Amount</th>
                    <th class="text-right">Outstanding Balance</th>
                </tr>
            @endif
        </thead>
        <tbody>
            @forelse($data as $row)
                @if($reportType === 'client_dues')
                    <tr>
                        <td class="font-bold">{{ $row['client_name'] }}</td>
                        <td>{{ $row['company_name'] }}</td>
                        <td class="text-center">{{ $row['services_count'] }}</td>
                        <td class="text-right">${{ number_format($row['total_value'], 2) }}</td>
                        <td class="text-right text-success">${{ number_format($row['total_paid'], 2) }}</td>
                        <td class="text-right text-danger">${{ number_format($row['balance'], 2) }}</td>
                    </tr>
                @elseif($reportType === 'service_revenue')
                    <tr>
                        <td class="font-bold">{{ $row['type'] }}</td>
                        <td class="text-center">{{ $row['count'] }}</td>
                        <td class="text-right">${{ number_format($row['revenue'], 2) }}</td>
                        <td class="text-right">${{ number_format($row['total_with_vat'], 2) }}</td>
                        <td class="text-right text-success">${{ number_format($row['paid'], 2) }}</td>
                        <td class="text-right text-danger">${{ number_format($row['balance'], 2) }}</td>
                    </tr>
                @elseif($reportType === 'monthly_renewals')
                    <tr>
                        <td class="font-bold">{{ $row['month'] }}</td>
                        <td class="text-center">{{ $row['count'] }}</td>
                        <td class="text-right">${{ number_format($row['total_value'], 2) }}</td>
                        <td class="text-center text-success">{{ $row['renewed_count'] }}</td>
                        <td class="text-center text-danger">{{ $row['pending_count'] }}</td>
                    </tr>
                @elseif($reportType === 'vat_summary')
                    <tr class="{{ $row['status'] === 'Total VAT Liability' ? 'total-row' : '' }}">
                        <td class="font-bold">{{ $row['status'] }}</td>
                        <td class="text-center">{{ $row['count'] }}</td>
                        <td class="text-right">${{ number_format($row['amount'], 2) }}</td>
                    </tr>
                @elseif($reportType === 'pending_payments')
                    <tr>
                        <td class="font-bold">{{ $row['client_name'] }}</td>
                        <td>{{ $row['company_name'] }}</td>
                        <td>{{ $row['type'] }}</td>
                        <td class="text-center">{{ $row['end_date'] }}</td>
                        <td class="text-right">${{ number_format($row['total'], 2) }}</td>
                        <td class="text-right text-success">${{ number_format($row['paid'], 2) }}</td>
                        <td class="text-right text-danger">${{ number_format($row['balance'], 2) }}</td>
                    </tr>
                @endif
            @empty
                <tr>
                    <td colspan="10" class="text-center" style="padding: 20px;">No records found matching report criteria.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        AIWA Agency Dashboard - Confidential Financial Document - Page 1 of 1
    </div>

</body>
</html>
